version: "3.3"

services:
    web-server:
        build:
            context: .
            dockerfile: docker/nginx.dockerfile
        ports:
            - 80:80
        links:
            - fpm
        volumes:
            - ./:/var/www/laravel-docker
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - mysql
    postgres:
        platform: linux/x86_64
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=crm_vlad
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - ./docker/postgres/datadir:/var/lib/postgresql/data
    mysql:
      platform: linux/x86_64
      image: mysql:5.7
      ports:
        - 33061:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=crm_vlad
